package gui;

import objects.Products;

/**
 * Settings window frame class
 * @author Hariton Andrei Marius
 */
public class Settings extends javax.swing.JFrame {
    // TreeMap of Products
    private Products products;
    // The manager
    private Manager manager;
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    /**
     * Setter for products
     * @param products The products
     */
    public void setProducts(Products products) {
        this.products = products;
    }
    
    /**
     * Setter for manager
     * @param manager The manager
     */
    public void setManager(Manager manager) {
        this.manager = manager;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        deleteProductsButton = new javax.swing.JButton();
        deleteProductsLabel = new javax.swing.JLabel();
        cleanControlsButton = new javax.swing.JButton();
        cleanControlsLabel = new javax.swing.JLabel();
        updateListButton = new javax.swing.JButton();
        updateListLabel = new javax.swing.JLabel();
        updateInfoButton = new javax.swing.JButton();
        updateInfoLabel = new javax.swing.JLabel();
        saveDataButton = new javax.swing.JButton();
        saveDataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setAlwaysOnTop(true);
        setResizable(false);

        infoLabel.setBackground(new java.awt.Color(204, 204, 204));
        infoLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 153, 51));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("ShopManager by Hariton Andrei Marius on 30/04/2016.");

        deleteProductsButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        deleteProductsButton.setText("Delete products");
        deleteProductsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductsButtonActionPerformed(evt);
            }
        });

        deleteProductsLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        deleteProductsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deleteProductsLabel.setText("You can restore them yet (on the manager).");

        cleanControlsButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cleanControlsButton.setText("Clean controls");
        cleanControlsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanControlsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanControlsButtonActionPerformed(evt);
            }
        });

        cleanControlsLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cleanControlsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cleanControlsLabel.setText("Cleans the controls panel into the manager.");

        updateListButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        updateListButton.setText("Update list");
        updateListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateListButtonActionPerformed(evt);
            }
        });

        updateListLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        updateListLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        updateListLabel.setText("Updates the list panel into the manager.");

        updateInfoButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        updateInfoButton.setText("Update info");
        updateInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoButtonActionPerformed(evt);
            }
        });

        updateInfoLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        updateInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        updateInfoLabel.setText("Updates the info panel into the manager.");

        saveDataButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        saveDataButton.setText("Save data");
        saveDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataButtonActionPerformed(evt);
            }
        });

        saveDataLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        saveDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saveDataLabel.setText("Saves all data into binary files.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanControlsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteProductsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteProductsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanControlsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteProductsButton)
                    .addComponent(deleteProductsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanControlsButton)
                    .addComponent(cleanControlsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateListButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateInfoButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveDataButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductsButtonActionPerformed
        manager.deleteAllProducts();
    }//GEN-LAST:event_deleteProductsButtonActionPerformed

    private void cleanControlsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanControlsButtonActionPerformed
        manager.cleanControls();
    }//GEN-LAST:event_cleanControlsButtonActionPerformed

    private void updateListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateListButtonActionPerformed
        manager.updateList();
    }//GEN-LAST:event_updateListButtonActionPerformed

    private void updateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoButtonActionPerformed
        manager.updateInfo();
    }//GEN-LAST:event_updateInfoButtonActionPerformed

    private void saveDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataButtonActionPerformed
        manager.updateFiles();
    }//GEN-LAST:event_saveDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Settings().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanControlsButton;
    private javax.swing.JLabel cleanControlsLabel;
    private javax.swing.JButton deleteProductsButton;
    private javax.swing.JLabel deleteProductsLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton saveDataButton;
    private javax.swing.JLabel saveDataLabel;
    private javax.swing.JButton updateInfoButton;
    private javax.swing.JLabel updateInfoLabel;
    private javax.swing.JButton updateListButton;
    private javax.swing.JLabel updateListLabel;
    // End of variables declaration//GEN-END:variables
}
